### ISSUE TITLE
Error when navigating with arrow keys at bottom of list

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levurehelper-dataview_tree#4]
This happens in the example stack with the file browser and the stack browser, but not with the others, and I'm not sure why, yet.
1. Select a row.
2. Use the down cursor key until you get to the bottom of the current page (or up until you get to the top of the current page)
3. The following error appears:
```
Type	Function: error in function handler
Object	DataView Behavior
Line	put round(aeEaseInOUt(pScrollFrom, pScrollTo, kAnimationLength, pLastTime - pPhaseStart, theExponent)) into theValue
Hint	aeEaseInOUt
```

**Comment by trevordevore** [comment]
It is because the `viewProp["animate selections"]` property is set to true and the animationEngine library isn't part of the project. I just pushed a commit that fixes it.
